eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
resilience4j.circuitbreaker:
  instances:
    BusinessCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 3s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10